[BitTorrent]
Session\AdditionalTrackers=udp://tracker.opentrackr.org:1337/announce\nudp://open.demonii.com:1337/announce\nudp://open.stealth.si:80/announce\nudp://tracker.torrent.eu.org:451/announce\nudp://explodie.org:6969/announce\nudp://tracker1.bt.moack.co.kr:80/announce\nudp://tracker-udp.gbitt.info:80/announce\nudp://open.tracker.cl:1337/announce\nudp://tracker.auctor.tv:6969/announce\nhttp://tracker.opentrackr.org:1337/announce\nudp://tracker2.dler.org:80/announce\nudp://zer0day.ch:1337/announce\nudp://tracker.qu.ax:6969/announce\nudp://tracker.wildkat.net:6969/announce
Session\BTProtocol=Both
Session\DHT=true
Session\Encryption=1
Session\LSD=true
Session\MaxConnections=800
Session\MaxConnectionsPerTorrent=100
Session\PEX=true
Session\QueueingSystemEnabled=false

[Meta]
MigrationVersion=6

[Preferences]
Download\SavePath=/home/sherlockguo/downloads/
General\Locale=zh_CN
WebUI\AlternativeUIEnabled=true
WebUI\RootFolder=/home/sherlockguo/.config/qBittorrent/vuetorrent/
